# NumPy Exercises 


#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create an array of all the even integers from 10 to 50

In [16]:
array=np.arange(10,50,2)
print("Array of all the even integers from 10 to 50")
print(array)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
my_matrix
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [20]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [22]:
np.random.rand(2)

array([0.73590199, 0.89049564])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
r = np.random.normal(size=25)
print(r)

[ 0.19104022 -0.18368359 -0.43044261 -0.77378985  0.78948799 -0.38826428
 -1.56430485 -0.53579337  0.08905677  1.02619382  0.20040636 -0.70543729
 -1.83766315 -0.84035081  3.12703538 -1.14712246 -0.60748518 -1.64161452
 -2.47012169  0.4977517   1.79835842  0.22017481  0.70763709 -0.07653048
  0.98402005]


#### Create the following matrix:

In [15]:
>>> import numpy as np

#### Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
num_line = np.linspace(0, 1, 20)
print(num_line)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[0:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [ ]:
array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [38]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[1,2]

8

In [ ]:
8

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:2, 1].reshape(2,1)

array([[2],
       [7]])

In [ ]:
array([[2],
       [7]])

In [41]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2,:]

array([11, 12, 13, 14, 15])

In [ ]:
array([11, 12, 13, 14, 15])

In [42]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [43]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [44]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [45]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Great Job!